# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Update submodule
      run: |
        git submodule update --init --recursive --remote BigMission.Shared
    - name: dir
      run: |
        dir
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore RedMist.RMonitorRelay.sln
    - name: Build
      run: dotnet build RedMist.RMonitorRelay.sln --no-restore
